version: "3.7"
services:
  
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    secrets:
      - database-password
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=clarusway-1
    networks:
      - juiletnet

  app:
    image: mehmetafsar510/bookstore-api:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - juiletnet
volumes:
  database-data:

secrets:
  db-password:
    file: database/password.txt

networks:
  juiletnet:
    driver: bridge