apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-deployment
  labels:
    app: storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
      - name: storefront
        image: clarusway/clarusshop-storefront
        ports:
        - containerPort: 80