Resources:
  PackerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Packer_Group
  PackerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PackerPolicy
      Groups:
        - !Ref PackerGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - ec2:*
            Effect: Allow
            Resource: "*"
