---
# tasks file for react
# tasks file for /home/ec2-user/ansible/roles/react
- name: create build directory
  file:
    path: "{{ container_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
# at this point do not forget change DB_HOSenv variable for postgresql node
- name: copy files to the react node
  copy:
    src: ./client/
    dest: "{{ container_path }}"
- name: copy the Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ container_path }}"
- name: remove {{ container_name }} container if exists
  shell: "docker ps -q --filter 'name={container_name }}' | grep -q . && dockestop {{ container_name }} && docker rm -f{{ container_name }} && docker image rm -{{ image_name }} || echo 'Not Found'"
- name: build container image
  docker_image:
    name: "{{ image_name }}"
    build:
      path: "{{ container_path }}"
    source: build
    state: present
- name: Launch react docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    ports:
    - "3000:3000"

