version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1 
        networks:
            - clarusnet
    myapp:
        image: callahanclarus/bookstore-api:latest
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet
networks:
    clarusnet:
        driver: bridge