plugin: aws_ec2
regions:
  - "us-east-2"
keyed_groups:
  - key: tags.Name
  - key: tags.environment
  # postgresql, nodejs ve react ec2-lar key:environment, value: development olarak taglenecek
compose:
  ansible_host: public_ip_address