version: "3.7"

services:
    database:
        image: mysql:5.7
        volumes:
          - /my/own/datadir:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: phonebook
            MYSQL_USER: admin
            MYSQL_PASSWORD: Clarusway
            MYSQL_PORT: 3306
        networks:
            - clarusnet
            
    app:
        image: "${ECR_REGISTRY}/${APP_REPO_NAME}"
        restart: always
        environment:
            MYSQL_DATABASE_HOST: database
            MYSQL_DATABASE_USER: admin
            MYSQL_DATABASE_PASSWORD: Clarusway
            MYSQL_DATABASE_DB: phonebook
            MYSQL_DATABASE_PORT: 3306
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet
networks:
    clarusnet:
        driver: bridge



        