apiVersion: v1
kind: Service
metadata:
  name: clarus-db-service
  labels:
    name: clarus-db-service
spec:
  type: ClusterIP
  selector:
    app: clarus-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306