apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: clarusways/todoapi-pod
        ports:
        - containerPort: 80
        env:
        #- name: MYSQL_DATABASE_HOST
        #  value: clarus-db-service #.default.svc.cluster.local
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: todoapi-configmap
              key: DATABASE_URL         
        #- name: MYSQL_DATABASE
        #  value: todo_db
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: todoapi-configmap
              key: DB
        #- name: MYSQL_USER
        #  value: clarusway
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: todoapi-configmap
              key: USER
        #- name: MYSQL_PASSWORD
        #  value: Clarusway_1
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todoapi-secret
              key: mysql-admin-password