---
AWSTemplateFormatVersion: '2010-09-09'
Description: KMS Key
Parameters:
  Key:
    Type: String
  Value:
    Type: String
Resources:
  myKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref 'AWS::StackName'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
      Tags:
        - Key: !Ref Key
          Value: !Ref Value
  myAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}
      TargetKeyId:
        Ref: myKey
Outputs: 
  KmsId: 
    Description: "KMS ID"
    Value: 
      Ref: "myKey"