---
AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Queue
Parameters:
  QueueName:
    Type: String
    Description: Name of SQS Queue
    Default: "SampleQueue"
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - ''
        - - !Ref QueueName
          - Ref: AWS::StackName
Outputs:
  QueueName:
    Value:
      Ref: MyQueue


